import React from 'react';
import type { RichTextFieldProps } from '../types.js';

/**
 * Renders rich text/HTML content from the CMS.
 * Uses dangerouslySetInnerHTML — content is generated by the CMS rich text editor.
 *
 * @example
 * // Basic usage
 * <RichTextField value={post.content} />
 *
 * // With Tailwind Typography (recommended for blog posts)
 * <RichTextField value={post.content} prose />
 *
 * // With a custom class
 * <RichTextField value={post.content} className="my-content-styles" />
 */
export function RichTextField({ value, className, prose = false }: RichTextFieldProps) {
  if (!value) return null;

  const classes = [prose ? 'prose' : '', className].filter(Boolean).join(' ') || undefined;

  return (
    <div
      className={classes}
      dangerouslySetInnerHTML={{ __html: value }}
    />
  );
}
