import React from 'react';
import type { RichTextFieldProps } from '../types.js';

/**
 * CSS baseline for unstyled rich text content produced by the CMS.
 *
 * Inject this into your global stylesheet (or a <style> tag) when you are NOT
 * using Tailwind Typography (`prose`). It targets `[data-cms-rich-text]` to
 * avoid collisions with the rest of your styles.
 *
 * @example
 * // In your global CSS file:
 * import { RICH_TEXT_BASE_CSS } from '@miso-software/headless-cms-core/ui';
 * // paste the string into a <style> tag or CSS-in-JS solution
 *
 * // Or with a <style> tag in your layout:
 * <style dangerouslySetInnerHTML={{ __html: RICH_TEXT_BASE_CSS }} />
 */
export const RICH_TEXT_BASE_CSS = `
[data-cms-rich-text] code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 0.875em;
  background-color: rgba(0, 0, 0, 0.06);
  padding: 0.15em 0.35em;
  border-radius: 3px;
}
[data-cms-rich-text] pre {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 0.875em;
  background-color: rgba(0, 0, 0, 0.06);
  padding: 1em 1.25em;
  border-radius: 6px;
  overflow-x: auto;
  white-space: pre;
}
[data-cms-rich-text] pre code {
  background: none;
  padding: 0;
  font-size: inherit;
  border-radius: 0;
}
[data-cms-rich-text] blockquote {
  border-left: 4px solid rgba(0, 0, 0, 0.15);
  padding-left: 1em;
  margin-left: 0;
  font-style: italic;
  opacity: 0.8;
}
[data-cms-rich-text] img {
  max-width: 100%;
  height: auto;
}
`.trim();

/**
 * Renders rich text/HTML content from the CMS.
 * Uses dangerouslySetInnerHTML — content is generated by the CMS rich text editor
 * and is trusted server-side output.
 *
 * The CMS rich text editor can produce the following HTML:
 *
 * **Block elements**
 * - `<p>` paragraphs (may have `style="text-align: center|right|justify"`)
 * - `<h1>`, `<h2>`, `<h3>` headings (may have text-align style)
 * - `<ul>`, `<ol>`, `<li>` lists
 * - `<blockquote>` block quotes
 * - `<hr>` horizontal rules
 * - `<pre><code>` code blocks
 *
 * **Inline elements**
 * - `<strong>` bold
 * - `<em>` italic
 * - `<u>` underline
 * - `<s>` strikethrough
 * - `<sub>` subscript
 * - `<sup>` superscript
 * - `<code>` inline code
 * - `<a href="...">` links
 * - `<span style="color: #hex">` text colour
 * - `<mark style="background-color: #hex">` highlighted text
 *
 * **Media**
 * - `<img src="...">` — may include `style="width: X%; height: auto; display: block;"`
 *   when the editor user resized the image
 *
 * @example
 * // Basic — browser defaults apply
 * <RichTextField value={post.content} />
 *
 * // Recommended for blog posts: Tailwind Typography handles all elements beautifully
 * <RichTextField value={post.content} prose />
 *
 * // Without Tailwind Typography — add RICH_TEXT_BASE_CSS to your global styles
 * // for proper code block and blockquote styling:
 * import { RICH_TEXT_BASE_CSS } from '@miso-software/headless-cms-core/ui';
 * <style dangerouslySetInnerHTML={{ __html: RICH_TEXT_BASE_CSS }} />
 * <RichTextField value={post.content} />
 *
 * // Custom class
 * <RichTextField value={post.content} className="my-content my-content--blog" />
 */
export function RichTextField({ value, className, prose = false }: RichTextFieldProps) {
  if (!value) return null;

  const classes = [prose ? 'prose' : '', className].filter(Boolean).join(' ') || undefined;

  return (
    <div
      className={classes}
      data-cms-rich-text="true"
      dangerouslySetInnerHTML={{ __html: value }}
    />
  );
}
